# Copyright 2026 Shinsuke Mori
# SPDX-License-Identifier: Apache-2.0
"""Regenerate the shipped models.dev cost snapshot (``costs_gen.py``).

Emits ``src/llm_catalog/core/costs_gen.py``: a snapshot of the models.dev
price sheets for the bundled vendors, so a model whose config omits ``cost``
still surfaces a price sheet through :class:`~llm_catalog.core.ResolvedModel`
(see ``costs.py``). models.dev provider ids match :data:`VendorName` 1:1;
``openai-compatible`` is skipped because it names a protocol, not an upstream
with a price list. Mirrors ai-sdk-catalog's ``scripts/generate-costs.ts`` so
both ecosystems embed the same sheets.

Run from the repository root, then format the output (git history of the
generated file tells you how stale the snapshot is):

    uv run python packages/llm-catalog-core/scripts/generate_costs.py
    uv run ruff format packages/llm-catalog-core/src/llm_catalog/core/costs_gen.py

Every snapshotted price passes the :class:`ModelCost` schema, so a models.dev
unit mix-up (or a price above the sanity cap) fails the generation instead of
shipping.
"""

from pathlib import Path
from typing import Any, get_args

import httpx

from llm_catalog.core.config import ModelCost, VendorName

API_URL = "https://models.dev/api.json"

# Vendors with a models.dev price list (all but `openai-compatible`).
VENDORS = [v for v in get_args(VendorName) if v != "openai-compatible"]

# (models.dev bucket, this config's camelCase bucket)
_BUCKETS = (
    ("input", "input"),
    ("output", "output"),
    ("cache_read", "cacheRead"),
    ("cache_write", "cacheWrite"),
)

_HEADER = '''# Copyright 2026 Shinsuke Mori
# SPDX-License-Identifier: Apache-2.0
"""The embedded models.dev price snapshot.

@generated by ``scripts/generate_costs.py`` — do not edit by hand. Price
sheets snapshotted from https://models.dev/api.json (USD per 1M tokens,
camelCase buckets matching :class:`~llm_catalog.core.ModelCost`): every
bundled vendor's text-outputting models with a price list. Refresh:

    uv run python packages/llm-catalog-core/scripts/generate_costs.py
    uv run ruff format packages/llm-catalog-core/src/llm_catalog/core/costs_gen.py
"""

__all__ = ["MODEL_COSTS"]

# vendor -> model id -> price sheet.
MODEL_COSTS: dict[str, dict[str, dict[str, float]]] = {
'''


def _sheet_of(model: Any) -> dict[str, float] | None:
    """One model's price sheet, or None when it has no price or no text output.

    Models that don't output text (image generation, TTS, video) are skipped —
    the catalog hands out language models, so their sheets would be dead weight.
    """
    if not isinstance(model, dict):
        return None
    cost = model.get("cost")
    modalities = model.get("modalities") or {}
    if not isinstance(cost, dict) or "text" not in (modalities.get("output") or []):
        return None
    sheet = {dst: cost[src] for src, dst in _BUCKETS if cost.get(src) is not None}
    if not sheet:
        return None
    ModelCost.model_validate(sheet)  # bounds check: a unit mix-up fails here
    return sheet


def build_costs_module(api: Any) -> str:
    """Build the generated module's source from the models.dev dump."""
    lines = [_HEADER]
    for vendor in VENDORS:
        provider = api.get(vendor)
        if provider is None:
            raise ValueError(f'models.dev has no "{vendor}" provider.')
        models = provider.get("models") or {}
        entries = []
        for model_id in sorted(models):
            sheet = _sheet_of(models[model_id])
            if sheet is not None:
                entries.append(f'        "{model_id}": {sheet!r},')
        if entries:
            lines.append(f'    "{vendor}": {{')
            lines.extend(entries)
            lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    response = httpx.get(API_URL, timeout=60)
    response.raise_for_status()
    out = (
        Path(__file__).resolve().parents[1]
        / "src"
        / "llm_catalog"
        / "core"
        / "costs_gen.py"
    )
    out.write_text(build_costs_module(response.json()), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
