# Copyright 2026 Shinsuke Mori
# SPDX-License-Identifier: Apache-2.0
"""Embedded models.dev price sheets for models whose config omits ``cost``.

Mirrors ai-sdk-catalog's fallback exactly: a model without an explicit
``cost`` gets the snapshot sheet (``costs_gen.py``) matching its vendor — a
direct provider's vendor, or the backend's vendor for a gateway model — and
its model id. The match is exact: models.dev spells ids the way each vendor
does, so a config using vendor ids matches as-is. No sheet exists for the
``openai-compatible`` vendor (it names a protocol, not an upstream), for a
direct provider whose id is not a bundled vendor, or for a model id
models.dev does not list — there the cost simply stays absent. An explicit
``cost`` in the config always wins; the fallback is applied at resolution
time by :class:`~llm_catalog.core.Catalog`.
"""

from typing import get_args

from .config import ModelCost, ModelEntry, Provider, VendorName, vendor_block_of
from .costs_gen import MODEL_COSTS

__all__ = ["cost_vendor_of", "default_cost_of"]

_VENDORS: frozenset[str] = frozenset(get_args(VendorName))


def cost_vendor_of(provider: Provider, model: ModelEntry) -> str | None:
    """Return the vendor whose price sheet applies to a model, if any.

    A direct provider's vendor (defaulting to the provider id, when that names
    a bundled vendor), or the backend's vendor for a gateway model.
    """
    if provider.gateway is not None:
        if model.backend is None:
            return None
        backend = provider.gateway.backends.get(model.backend)
        return None if backend is None else backend.vendor
    block = vendor_block_of(provider)
    vendor = (block.id if block is not None else None) or provider.id
    return vendor if vendor in _VENDORS else None


def default_cost_of(provider: Provider, model: ModelEntry) -> ModelCost | None:
    """Return the embedded price sheet for a model whose config omits ``cost``.

    The model's id looked up under its vendor (see :func:`cost_vendor_of`) in
    the snapshot generated by ``scripts/generate_costs.py``. ``None`` when the
    vendor is unknown or models.dev lists no price for the id.
    """
    vendor = cost_vendor_of(provider, model)
    if vendor is None:
        return None
    sheet = MODEL_COSTS.get(vendor, {}).get(model.id)
    return None if sheet is None else ModelCost.model_validate(sheet)
